name: slot-mar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - pip
  - numpy=1.26.4
  - pillow=10.3.0
  - pycocotools=2.0.10
  - pyyaml=6.0.1
  - scipy=1.13.0
  - tqdm=4.67.1
  - pip:
      - diffusers==0.33.1
      - einops==0.8.0
      - omegaconf==2.3.0
      - termcolor==3.3.0
      - torch==2.7.0
      - torchmetrics==1.3.2
      - torchvision==0.22.0
      - wandb==0.24.1
